name: Generate Pacman Contribution Graph

on:
  # Run automatically every day
  schedule:
    - cron: "0 0 * * *"
  # Allow manual trigger
  workflow_dispatch:
  # Run on push to main/master
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm install @joshualine/github-spray @actions/core @actions/github
      
    - name: Generate Pacman Pattern
      uses: jasineri/github-contributions-canvas@v1.0.0
      with:
        github_user_name: ${{ github.repository_owner }}
        output_file_path: 'pacman-contribution-graph.svg'
        theme: 'pacman'
        
    - name: Generate Dark Mode Version
      uses: jasineri/github-contributions-canvas@v1.0.0
      with:
        github_user_name: ${{ github.repository_owner }}
        output_file_path: 'pacman-contribution-graph-dark.svg'
        theme: 'pacman-dark'
        
    - name: Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        mkdir -p output
        mv pacman-contribution-graph.svg output/
        mv pacman-contribution-graph-dark.svg output/
        
        git add output/
        git commit -m "Update Pacman contribution graph" || echo "No changes to commit"
        git push
```